### ISSUE TITLE
:unicorn: SPIKE: Add support from AFlex to Hyrax for rendering the attribute_rows dynamically

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/amigos#10]
[SOW](https://github.com/scientist-softserv/amigos/issues/1)

# Summary

In Allinson Flex, we can parse render_as settings such as faceted, HTML, etc.
Hyrax needs to be dynamic per the definitions defined by the profile or schema.

- [ ] views should be dynamic 
- [ ] handle faceted in a separate ticket

Allinson Flex has extra partials to handle dynamic forms. This is already supported in Hyrax.

# Acceptance Criteria

- [ ] The properties should be displayed as defined by the metadata schema files.
- [ ] Determine a plan to migrate the AFlex rendering to Hyrax
  - [ ] Can this apply to `SimpleSchema` or how do we separate the two
  - [ ] Add details to #11

# Screenshots or Video

# Testing Instructions

# Notes
Allinson Flex's views differences from Hyrax/Hyku:
- `layouts/_head_tag_content` has tinymce editor added - why? probably not needed at this point.
- Admin set control tabs includes a `metadata_context` tab - not needed until we do contexts work
- admin dashboard sidebar - will be moved to gem other than what is already done
- my/works & default/works: `default_group` & `list_works` includes profile_version on lists
- `records/edit_fields` directory: `default` display an one term generically
- handle rights_statement (see utk's `rights_statement.html.erb` partial)
- how to support based near?
- allinson flex apparently doesn't handle remote controlled vocabulary field views - see subject in utk
- `profile_version` show version on work form ([ticket](https://github.com/scientist-softserv/amigos/issues/23))
- Do we need anything re: utk's custom partials? why are other terms defined in utk? do they have to be? dates, resource_link (read_only), spatial, utk's custom terms
- How can we incorporate internalization for dynamic labels?
- AllinsonFlex doesn't support dynamic collections & file sets => need to extend dynamic views

**Comment by laritakr** [comment]
Allinson Flex's views differences from Hyrax/Hyku:
- `layouts/_head_tag_content` has tinymce editor added - why? probably not needed at this point.
- Admin set control tabs includes a `metadata_context` tab - not needed until we do contexts work
- admin dashboard sidebar - will be moved to gem other than what is already done
- my/works & default/works: `default_group` & `list_works` includes profile_version on lists
- `records/edit_fields` directory: `default` display an one term generically
- handle rights_statement (see utk's `rights_statement.html.erb` partial)
- how to support based near?
- allinson flex apparently doesn't handle remote controlled vocabulary field views - see subject in utk
- `profile_version` show version on work form ([ticket](https://github.com/scientist-softserv/amigos/issues/23))
- Do we need anything re: utk's custom partials? why are other terms defined in utk? do they have to be? dates, resource_link (read_only), spatial, utk's custom terms
- How can we incorporate internalization for dynamic labels?

## Tasks

- [ ] Implement `view_properties` method on a presenter's schema service
- [ ] Convert `attribute_rows` partial to dynamic
    - Use `view_properties` method
    - Display terms dynamically based on schemas (see app/views/records/edit_fields/_default.html.erb)
- Implement custom partials for terms which don't work generically: 
     - [ ] rights statement
     - [ ] based near
     - [ ] remote authority vocabularies
     - any other? 
         - [ ] UTK has others which don't seem necessary at first glance
         - [ ] UTK has a readonly term... is this needed?
