### ISSUE TITLE
SOW: Additional Work Types into Core Hyku

### ISSUE THREAD

**Issue by jillpe** [notch8/amigos#3]
## Summary
SoftServ will bring the ETD and OER work types from Hyku Commons into core Hyku.

## Acceptance Criteria
- [ ] ETD work type is available in core Hyku and is based on Hyku Commons
- [ ] OER work type is available in core Hyku and is based on Hyku Commons

## TASKS
- [x] #13 

## Testing Criteria
- [ ] UI creation
- [ ] UI batch creation - [note, this is not yet supported](https://github.com/scientist-softserv/amigos/issues/55)
- [ ] Bulkrax import - [bug ticket](https://github.com/scientist-softserv/amigos/issues/56)
- [ ] Work show page renders correctly
- [ ] User can add the work types as child works or to collections
